/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutVisionMissionRouteImport } from './routes/about.vision-mission'
import { Route as AboutSexualHarassmentRouteImport } from './routes/about.sexual-harassment'
import { Route as AboutPrincipalRouteImport } from './routes/about.principal'
import { Route as AboutIcarRouteImport } from './routes/about.icar'
import { Route as AboutChairmanRouteImport } from './routes/about.chairman'
import { Route as AboutBoardOfStudiesRouteImport } from './routes/about.board-of-studies'
import { Route as AboutApprovalsRouteImport } from './routes/about.approvals'
import { Route as AboutAntiRaggingRouteImport } from './routes/about.anti-ragging'
import { Route as AcademicsCoursesRouteImport } from './routes/academics.courses'
import { Route as AcademicsNssRouteImport } from './routes/academics.nss'
import { Route as AcademicsComputerCenterRouteImport } from './routes/academics.computer-center'
import { Route as AcademicsLibraryRouteImport } from './routes/academics.library'
import { Route as AcademicsSmartClassRouteImport } from './routes/academics.smart-class'
import { Route as AcademicsPhysicalEducationRouteImport } from './routes/academics.physical-education'
import { Route as AcademicsYogaRouteImport } from './routes/academics.yoga'
import { Route as AcademicsExamPatternRouteImport } from './routes/academics.exam-pattern'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVisionMissionRoute = AboutVisionMissionRouteImport.update({
  id: '/about/vision-mission',
  path: '/about/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSexualHarassmentRoute = AboutSexualHarassmentRouteImport.update({
  id: '/about/sexual-harassment',
  path: '/about/sexual-harassment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPrincipalRoute = AboutPrincipalRouteImport.update({
  id: '/about/principal',
  path: '/about/principal',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIcarRoute = AboutIcarRouteImport.update({
  id: '/about/icar',
  path: '/about/icar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutChairmanRoute = AboutChairmanRouteImport.update({
  id: '/about/chairman',
  path: '/about/chairman',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutBoardOfStudiesRoute = AboutBoardOfStudiesRouteImport.update({
  id: '/about/board-of-studies',
  path: '/about/board-of-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutApprovalsRoute = AboutApprovalsRouteImport.update({
  id: '/about/approvals',
  path: '/about/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAntiRaggingRoute = AboutAntiRaggingRouteImport.update({
  id: '/about/anti-ragging',
  path: '/about/anti-ragging',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsCoursesRoute = AcademicsCoursesRouteImport.update({
  id: '/academics/courses',
  path: '/academics/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsNssRoute = AcademicsNssRouteImport.update({
  id: '/academics/nss',
  path: '/academics/nss',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsComputerCenterRoute = AcademicsComputerCenterRouteImport.update({
  id: '/academics/computer-center',
  path: '/academics/computer-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsLibraryRoute = AcademicsLibraryRouteImport.update({
  id: '/academics/library',
  path: '/academics/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsSmartClassRoute = AcademicsSmartClassRouteImport.update({
  id: '/academics/smart-class',
  path: '/academics/smart-class',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsPhysicalEducationRoute = AcademicsPhysicalEducationRouteImport.update({
  id: '/academics/physical-education',
  path: '/academics/physical-education',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsYogaRoute = AcademicsYogaRouteImport.update({
  id: '/academics/yoga',
  path: '/academics/yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsExamPatternRoute = AcademicsExamPatternRouteImport.update({
  id: '/academics/exam-pattern',
  path: '/academics/exam-pattern',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/anti-ragging': typeof AboutAntiRaggingRoute
  '/about/approvals': typeof AboutApprovalsRoute
  '/about/board-of-studies': typeof AboutBoardOfStudiesRoute
  '/about/chairman': typeof AboutChairmanRoute
  '/about/icar': typeof AboutIcarRoute
  '/about/principal': typeof AboutPrincipalRoute
  '/about/sexual-harassment': typeof AboutSexualHarassmentRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/about/': typeof AboutIndexRoute
  '/academics/courses': typeof AcademicsCoursesRoute
  '/academics/nss': typeof AcademicsNssRoute
  '/academics/computer-center': typeof AcademicsComputerCenterRoute
  '/academics/library': typeof AcademicsLibraryRoute
  '/academics/smart-class': typeof AcademicsSmartClassRoute
  '/academics/physical-education': typeof AcademicsPhysicalEducationRoute
  '/academics/yoga': typeof AcademicsYogaRoute
  '/academics/exam-pattern': typeof AcademicsExamPatternRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about/anti-ragging': typeof AboutAntiRaggingRoute
  '/about/approvals': typeof AboutApprovalsRoute
  '/about/board-of-studies': typeof AboutBoardOfStudiesRoute
  '/about/chairman': typeof AboutChairmanRoute
  '/about/icar': typeof AboutIcarRoute
  '/about/principal': typeof AboutPrincipalRoute
  '/about/sexual-harassment': typeof AboutSexualHarassmentRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/about': typeof AboutIndexRoute
  '/academics/courses': typeof AcademicsCoursesRoute
  '/academics/nss': typeof AcademicsNssRoute
  '/academics/computer-center': typeof AcademicsComputerCenterRoute
  '/academics/library': typeof AcademicsLibraryRoute
  '/academics/smart-class': typeof AcademicsSmartClassRoute
  '/academics/physical-education': typeof AcademicsPhysicalEducationRoute
  '/academics/yoga': typeof AcademicsYogaRoute
  '/academics/exam-pattern': typeof AcademicsExamPatternRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/anti-ragging': typeof AboutAntiRaggingRoute
  '/about/approvals': typeof AboutApprovalsRoute
  '/about/board-of-studies': typeof AboutBoardOfStudiesRoute
  '/about/chairman': typeof AboutChairmanRoute
  '/about/icar': typeof AboutIcarRoute
  '/about/principal': typeof AboutPrincipalRoute
  '/about/sexual-harassment': typeof AboutSexualHarassmentRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/about/': typeof AboutIndexRoute
  '/academics/courses': typeof AcademicsCoursesRoute
  '/academics/nss': typeof AcademicsNssRoute
  '/academics/computer-center': typeof AcademicsComputerCenterRoute
  '/academics/library': typeof AcademicsLibraryRoute
  '/academics/smart-class': typeof AcademicsSmartClassRoute
  '/academics/physical-education': typeof AcademicsPhysicalEducationRoute
  '/academics/yoga': typeof AcademicsYogaRoute
  '/academics/exam-pattern': typeof AcademicsExamPatternRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/anti-ragging'
    | '/about/approvals'
    | '/about/board-of-studies'
    | '/about/chairman'
    | '/about/icar'
    | '/about/principal'
    | '/about/sexual-harassment'
    | '/about/vision-mission'
    | '/about/'
    | '/academics/courses'
    | '/academics/nss'
    | '/academics/computer-center'
    | '/academics/library'
    | '/academics/smart-class'
    | '/academics/physical-education'
    | '/academics/yoga'
    | '/academics/exam-pattern'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about/anti-ragging'
    | '/about/approvals'
    | '/about/board-of-studies'
    | '/about/chairman'
    | '/about/icar'
    | '/about/principal'
    | '/about/sexual-harassment'
    | '/about/vision-mission'
    | '/about'
    | '/academics/courses'
    | '/academics/nss'
    | '/academics/computer-center'
    | '/academics/library'
    | '/academics/smart-class'
    | '/academics/physical-education'
    | '/academics/yoga'
    | '/academics/exam-pattern'
  id:
    | '__root__'
    | '/'
    | '/about/anti-ragging'
    | '/about/approvals'
    | '/about/board-of-studies'
    | '/about/chairman'
    | '/about/icar'
    | '/about/principal'
    | '/about/sexual-harassment'
    | '/about/vision-mission'
    | '/about/'
    | '/academics/courses'
    | '/academics/nss'
    | '/academics/computer-center'
    | '/academics/library'
    | '/academics/smart-class'
    | '/academics/physical-education'
    | '/academics/yoga'
    | '/academics/exam-pattern'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutAntiRaggingRoute: typeof AboutAntiRaggingRoute
  AboutApprovalsRoute: typeof AboutApprovalsRoute
  AboutBoardOfStudiesRoute: typeof AboutBoardOfStudiesRoute
  AboutChairmanRoute: typeof AboutChairmanRoute
  AboutIcarRoute: typeof AboutIcarRoute
  AboutPrincipalRoute: typeof AboutPrincipalRoute
  AboutSexualHarassmentRoute: typeof AboutSexualHarassmentRoute
  AboutVisionMissionRoute: typeof AboutVisionMissionRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AcademicsCoursesRoute: typeof AcademicsCoursesRoute
  AcademicsNssRoute: typeof AcademicsNssRoute
  AcademicsComputerCenterRoute: typeof AcademicsComputerCenterRoute
  AcademicsLibraryRoute: typeof AcademicsLibraryRoute
  AcademicsSmartClassRoute: typeof AcademicsSmartClassRoute
  AcademicsPhysicalEducationRoute: typeof AcademicsPhysicalEducationRoute
  AcademicsYogaRoute: typeof AcademicsYogaRoute
  AcademicsExamPatternRoute: typeof AcademicsExamPatternRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/vision-mission': {
      id: '/about/vision-mission'
      path: '/about/vision-mission'
      fullPath: '/about/vision-mission'
      preLoaderRoute: typeof AboutVisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/sexual-harassment': {
      id: '/about/sexual-harassment'
      path: '/about/sexual-harassment'
      fullPath: '/about/sexual-harassment'
      preLoaderRoute: typeof AboutSexualHarassmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/principal': {
      id: '/about/principal'
      path: '/about/principal'
      fullPath: '/about/principal'
      preLoaderRoute: typeof AboutPrincipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/icar': {
      id: '/about/icar'
      path: '/about/icar'
      fullPath: '/about/icar'
      preLoaderRoute: typeof AboutIcarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/chairman': {
      id: '/about/chairman'
      path: '/about/chairman'
      fullPath: '/about/chairman'
      preLoaderRoute: typeof AboutChairmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/board-of-studies': {
      id: '/about/board-of-studies'
      path: '/about/board-of-studies'
      fullPath: '/about/board-of-studies'
      preLoaderRoute: typeof AboutBoardOfStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/approvals': {
      id: '/about/approvals'
      path: '/about/approvals'
      fullPath: '/about/approvals'
      preLoaderRoute: typeof AboutApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/anti-ragging': {
      id: '/about/anti-ragging'
      path: '/about/anti-ragging'
      fullPath: '/about/anti-ragging'
      preLoaderRoute: typeof AboutAntiRaggingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/courses': {
      id: '/academics/courses'
      path: '/academics/courses'
      fullPath: '/academics/courses'
      preLoaderRoute: typeof AcademicsCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/nss': {
      id: '/academics/nss'
      path: '/academics/nss'
      fullPath: '/academics/nss'
      preLoaderRoute: typeof AcademicsNssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/computer-center': {
      id: '/academics/computer-center'
      path: '/academics/computer-center'
      fullPath: '/academics/computer-center'
      preLoaderRoute: typeof AcademicsComputerCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/library': {
      id: '/academics/library'
      path: '/academics/library'
      fullPath: '/academics/library'
      preLoaderRoute: typeof AcademicsLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/smart-class': {
      id: '/academics/smart-class'
      path: '/academics/smart-class'
      fullPath: '/academics/smart-class'
      preLoaderRoute: typeof AcademicsSmartClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/physical-education': {
      id: '/academics/physical-education'
      path: '/academics/physical-education'
      fullPath: '/academics/physical-education'
      preLoaderRoute: typeof AcademicsPhysicalEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/yoga': {
      id: '/academics/yoga'
      path: '/academics/yoga'
      fullPath: '/academics/yoga'
      preLoaderRoute: typeof AcademicsYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/exam-pattern': {
      id: '/academics/exam-pattern'
      path: '/academics/exam-pattern'
      fullPath: '/academics/exam-pattern'
      preLoaderRoute: typeof AcademicsExamPatternRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutAntiRaggingRoute: AboutAntiRaggingRoute,
  AboutApprovalsRoute: AboutApprovalsRoute,
  AboutBoardOfStudiesRoute: AboutBoardOfStudiesRoute,
  AboutChairmanRoute: AboutChairmanRoute,
  AboutIcarRoute: AboutIcarRoute,
  AboutPrincipalRoute: AboutPrincipalRoute,
  AboutSexualHarassmentRoute: AboutSexualHarassmentRoute,
  AboutVisionMissionRoute: AboutVisionMissionRoute,
  AboutIndexRoute: AboutIndexRoute,
  AcademicsCoursesRoute: AcademicsCoursesRoute,
  AcademicsNssRoute: AcademicsNssRoute,
  AcademicsComputerCenterRoute: AcademicsComputerCenterRoute,
  AcademicsLibraryRoute: AcademicsLibraryRoute,
  AcademicsSmartClassRoute: AcademicsSmartClassRoute,
  AcademicsPhysicalEducationRoute: AcademicsPhysicalEducationRoute,
  AcademicsYogaRoute: AcademicsYogaRoute,
  AcademicsExamPatternRoute: AcademicsExamPatternRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
