/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as LifePlacementRouteImport } from './routes/life.placement'
import { Route as LifeNewsletterRouteImport } from './routes/life.newsletter'
import { Route as LifeHostelRouteImport } from './routes/life.hostel'
import { Route as LifeFeePaymentRouteImport } from './routes/life.fee-payment'
import { Route as LifeEventsRouteImport } from './routes/life.events'
import { Route as LifeCulturalsRouteImport } from './routes/life.culturals'
import { Route as FarmsWeatherRouteImport } from './routes/farms.weather'
import { Route as FarmsSouthRouteImport } from './routes/farms.south'
import { Route as FarmsNorthRouteImport } from './routes/farms.north'
import { Route as DivisionsSocialScienceRouteImport } from './routes/divisions.social-science'
import { Route as DivisionsPlantProtectionRouteImport } from './routes/divisions.plant-protection'
import { Route as DivisionsHorticultureRouteImport } from './routes/divisions.horticulture'
import { Route as DivisionsCropManagementRouteImport } from './routes/divisions.crop-management'
import { Route as DivisionsCropImprovementRouteImport } from './routes/divisions.crop-improvement'
import { Route as DivisionsAgricultureEngineeringRouteImport } from './routes/divisions.agriculture-engineering'
import { Route as AcademicsYogaRouteImport } from './routes/academics.yoga'
import { Route as AcademicsSmartClassRouteImport } from './routes/academics.smart-class'
import { Route as AcademicsPhysicalEducationRouteImport } from './routes/academics.physical-education'
import { Route as AcademicsNssRouteImport } from './routes/academics.nss'
import { Route as AcademicsLibraryRouteImport } from './routes/academics.library'
import { Route as AcademicsExamPatternRouteImport } from './routes/academics.exam-pattern'
import { Route as AcademicsCoursesRouteImport } from './routes/academics.courses'
import { Route as AcademicsComputerCenterRouteImport } from './routes/academics.computer-center'
import { Route as AboutVisionMissionRouteImport } from './routes/about.vision-mission'
import { Route as AboutSexualHarassmentRouteImport } from './routes/about.sexual-harassment'
import { Route as AboutPrincipalRouteImport } from './routes/about.principal'
import { Route as AboutIcarRouteImport } from './routes/about.icar'
import { Route as AboutChairmanRouteImport } from './routes/about.chairman'
import { Route as AboutBoardOfStudiesRouteImport } from './routes/about.board-of-studies'
import { Route as AboutApprovalsRouteImport } from './routes/about.approvals'
import { Route as AboutAntiRaggingRouteImport } from './routes/about.anti-ragging'

const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const LifePlacementRoute = LifePlacementRouteImport.update({
  id: '/life/placement',
  path: '/life/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeNewsletterRoute = LifeNewsletterRouteImport.update({
  id: '/life/newsletter',
  path: '/life/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeHostelRoute = LifeHostelRouteImport.update({
  id: '/life/hostel',
  path: '/life/hostel',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeFeePaymentRoute = LifeFeePaymentRouteImport.update({
  id: '/life/fee-payment',
  path: '/life/fee-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeEventsRoute = LifeEventsRouteImport.update({
  id: '/life/events',
  path: '/life/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeCulturalsRoute = LifeCulturalsRouteImport.update({
  id: '/life/culturals',
  path: '/life/culturals',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsWeatherRoute = FarmsWeatherRouteImport.update({
  id: '/farms/weather',
  path: '/farms/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsSouthRoute = FarmsSouthRouteImport.update({
  id: '/farms/south',
  path: '/farms/south',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsNorthRoute = FarmsNorthRouteImport.update({
  id: '/farms/north',
  path: '/farms/north',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionsSocialScienceRoute = DivisionsSocialScienceRouteImport.update({
  id: '/divisions/social-science',
  path: '/divisions/social-science',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionsPlantProtectionRoute =
  DivisionsPlantProtectionRouteImport.update({
    id: '/divisions/plant-protection',
    path: '/divisions/plant-protection',
    getParentRoute: () => rootRouteImport,
  } as any)
const DivisionsHorticultureRoute = DivisionsHorticultureRouteImport.update({
  id: '/divisions/horticulture',
  path: '/divisions/horticulture',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionsCropManagementRoute = DivisionsCropManagementRouteImport.update({
  id: '/divisions/crop-management',
  path: '/divisions/crop-management',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionsCropImprovementRoute =
  DivisionsCropImprovementRouteImport.update({
    id: '/divisions/crop-improvement',
    path: '/divisions/crop-improvement',
    getParentRoute: () => rootRouteImport,
  } as any)
const DivisionsAgricultureEngineeringRoute =
  DivisionsAgricultureEngineeringRouteImport.update({
    id: '/divisions/agriculture-engineering',
    path: '/divisions/agriculture-engineering',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicsYogaRoute = AcademicsYogaRouteImport.update({
  id: '/academics/yoga',
  path: '/academics/yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsSmartClassRoute = AcademicsSmartClassRouteImport.update({
  id: '/academics/smart-class',
  path: '/academics/smart-class',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsPhysicalEducationRoute =
  AcademicsPhysicalEducationRouteImport.update({
    id: '/academics/physical-education',
    path: '/academics/physical-education',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicsNssRoute = AcademicsNssRouteImport.update({
  id: '/academics/nss',
  path: '/academics/nss',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsLibraryRoute = AcademicsLibraryRouteImport.update({
  id: '/academics/library',
  path: '/academics/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsExamPatternRoute = AcademicsExamPatternRouteImport.update({
  id: '/academics/exam-pattern',
  path: '/academics/exam-pattern',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsCoursesRoute = AcademicsCoursesRouteImport.update({
  id: '/academics/courses',
  path: '/academics/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsComputerCenterRoute = AcademicsComputerCenterRouteImport.update({
  id: '/academics/computer-center',
  path: '/academics/computer-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVisionMissionRoute = AboutVisionMissionRouteImport.update({
  id: '/about/vision-mission',
  path: '/about/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSexualHarassmentRoute = AboutSexualHarassmentRouteImport.update({
  id: '/about/sexual-harassment',
  path: '/about/sexual-harassment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPrincipalRoute = AboutPrincipalRouteImport.update({
  id: '/about/principal',
  path: '/about/principal',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIcarRoute = AboutIcarRouteImport.update({
  id: '/about/icar',
  path: '/about/icar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutChairmanRoute = AboutChairmanRouteImport.update({
  id: '/about/chairman',
  path: '/about/chairman',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutBoardOfStudiesRoute = AboutBoardOfStudiesRouteImport.update({
  id: '/about/board-of-studies',
  path: '/about/board-of-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutApprovalsRoute = AboutApprovalsRouteImport.update({
  id: '/about/approvals',
  path: '/about/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAntiRaggingRoute = AboutAntiRaggingRouteImport.update({
  id: '/about/anti-ragging',
  path: '/about/anti-ragging',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/about/anti-ragging': typeof AboutAntiRaggingRoute
  '/about/approvals': typeof AboutApprovalsRoute
  '/about/board-of-studies': typeof AboutBoardOfStudiesRoute
  '/about/chairman': typeof AboutChairmanRoute
  '/about/icar': typeof AboutIcarRoute
  '/about/principal': typeof AboutPrincipalRoute
  '/about/sexual-harassment': typeof AboutSexualHarassmentRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/academics/computer-center': typeof AcademicsComputerCenterRoute
  '/academics/courses': typeof AcademicsCoursesRoute
  '/academics/exam-pattern': typeof AcademicsExamPatternRoute
  '/academics/library': typeof AcademicsLibraryRoute
  '/academics/nss': typeof AcademicsNssRoute
  '/academics/physical-education': typeof AcademicsPhysicalEducationRoute
  '/academics/smart-class': typeof AcademicsSmartClassRoute
  '/academics/yoga': typeof AcademicsYogaRoute
  '/divisions/agriculture-engineering': typeof DivisionsAgricultureEngineeringRoute
  '/divisions/crop-improvement': typeof DivisionsCropImprovementRoute
  '/divisions/crop-management': typeof DivisionsCropManagementRoute
  '/divisions/horticulture': typeof DivisionsHorticultureRoute
  '/divisions/plant-protection': typeof DivisionsPlantProtectionRoute
  '/divisions/social-science': typeof DivisionsSocialScienceRoute
  '/farms/north': typeof FarmsNorthRoute
  '/farms/south': typeof FarmsSouthRoute
  '/farms/weather': typeof FarmsWeatherRoute
  '/life/culturals': typeof LifeCulturalsRoute
  '/life/events': typeof LifeEventsRoute
  '/life/fee-payment': typeof LifeFeePaymentRoute
  '/life/hostel': typeof LifeHostelRoute
  '/life/newsletter': typeof LifeNewsletterRoute
  '/life/placement': typeof LifePlacementRoute
  '/about/': typeof AboutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/about/anti-ragging': typeof AboutAntiRaggingRoute
  '/about/approvals': typeof AboutApprovalsRoute
  '/about/board-of-studies': typeof AboutBoardOfStudiesRoute
  '/about/chairman': typeof AboutChairmanRoute
  '/about/icar': typeof AboutIcarRoute
  '/about/principal': typeof AboutPrincipalRoute
  '/about/sexual-harassment': typeof AboutSexualHarassmentRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/academics/computer-center': typeof AcademicsComputerCenterRoute
  '/academics/courses': typeof AcademicsCoursesRoute
  '/academics/exam-pattern': typeof AcademicsExamPatternRoute
  '/academics/library': typeof AcademicsLibraryRoute
  '/academics/nss': typeof AcademicsNssRoute
  '/academics/physical-education': typeof AcademicsPhysicalEducationRoute
  '/academics/smart-class': typeof AcademicsSmartClassRoute
  '/academics/yoga': typeof AcademicsYogaRoute
  '/divisions/agriculture-engineering': typeof DivisionsAgricultureEngineeringRoute
  '/divisions/crop-improvement': typeof DivisionsCropImprovementRoute
  '/divisions/crop-management': typeof DivisionsCropManagementRoute
  '/divisions/horticulture': typeof DivisionsHorticultureRoute
  '/divisions/plant-protection': typeof DivisionsPlantProtectionRoute
  '/divisions/social-science': typeof DivisionsSocialScienceRoute
  '/farms/north': typeof FarmsNorthRoute
  '/farms/south': typeof FarmsSouthRoute
  '/farms/weather': typeof FarmsWeatherRoute
  '/life/culturals': typeof LifeCulturalsRoute
  '/life/events': typeof LifeEventsRoute
  '/life/fee-payment': typeof LifeFeePaymentRoute
  '/life/hostel': typeof LifeHostelRoute
  '/life/newsletter': typeof LifeNewsletterRoute
  '/life/placement': typeof LifePlacementRoute
  '/about': typeof AboutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/about/anti-ragging': typeof AboutAntiRaggingRoute
  '/about/approvals': typeof AboutApprovalsRoute
  '/about/board-of-studies': typeof AboutBoardOfStudiesRoute
  '/about/chairman': typeof AboutChairmanRoute
  '/about/icar': typeof AboutIcarRoute
  '/about/principal': typeof AboutPrincipalRoute
  '/about/sexual-harassment': typeof AboutSexualHarassmentRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/academics/computer-center': typeof AcademicsComputerCenterRoute
  '/academics/courses': typeof AcademicsCoursesRoute
  '/academics/exam-pattern': typeof AcademicsExamPatternRoute
  '/academics/library': typeof AcademicsLibraryRoute
  '/academics/nss': typeof AcademicsNssRoute
  '/academics/physical-education': typeof AcademicsPhysicalEducationRoute
  '/academics/smart-class': typeof AcademicsSmartClassRoute
  '/academics/yoga': typeof AcademicsYogaRoute
  '/divisions/agriculture-engineering': typeof DivisionsAgricultureEngineeringRoute
  '/divisions/crop-improvement': typeof DivisionsCropImprovementRoute
  '/divisions/crop-management': typeof DivisionsCropManagementRoute
  '/divisions/horticulture': typeof DivisionsHorticultureRoute
  '/divisions/plant-protection': typeof DivisionsPlantProtectionRoute
  '/divisions/social-science': typeof DivisionsSocialScienceRoute
  '/farms/north': typeof FarmsNorthRoute
  '/farms/south': typeof FarmsSouthRoute
  '/farms/weather': typeof FarmsWeatherRoute
  '/life/culturals': typeof LifeCulturalsRoute
  '/life/events': typeof LifeEventsRoute
  '/life/fee-payment': typeof LifeFeePaymentRoute
  '/life/hostel': typeof LifeHostelRoute
  '/life/newsletter': typeof LifeNewsletterRoute
  '/life/placement': typeof LifePlacementRoute
  '/about/': typeof AboutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/faculty'
    | '/gallery'
    | '/about/anti-ragging'
    | '/about/approvals'
    | '/about/board-of-studies'
    | '/about/chairman'
    | '/about/icar'
    | '/about/principal'
    | '/about/sexual-harassment'
    | '/about/vision-mission'
    | '/academics/computer-center'
    | '/academics/courses'
    | '/academics/exam-pattern'
    | '/academics/library'
    | '/academics/nss'
    | '/academics/physical-education'
    | '/academics/smart-class'
    | '/academics/yoga'
    | '/divisions/agriculture-engineering'
    | '/divisions/crop-improvement'
    | '/divisions/crop-management'
    | '/divisions/horticulture'
    | '/divisions/plant-protection'
    | '/divisions/social-science'
    | '/farms/north'
    | '/farms/south'
    | '/farms/weather'
    | '/life/culturals'
    | '/life/events'
    | '/life/fee-payment'
    | '/life/hostel'
    | '/life/newsletter'
    | '/life/placement'
    | '/about/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faculty'
    | '/gallery'
    | '/about/anti-ragging'
    | '/about/approvals'
    | '/about/board-of-studies'
    | '/about/chairman'
    | '/about/icar'
    | '/about/principal'
    | '/about/sexual-harassment'
    | '/about/vision-mission'
    | '/academics/computer-center'
    | '/academics/courses'
    | '/academics/exam-pattern'
    | '/academics/library'
    | '/academics/nss'
    | '/academics/physical-education'
    | '/academics/smart-class'
    | '/academics/yoga'
    | '/divisions/agriculture-engineering'
    | '/divisions/crop-improvement'
    | '/divisions/crop-management'
    | '/divisions/horticulture'
    | '/divisions/plant-protection'
    | '/divisions/social-science'
    | '/farms/north'
    | '/farms/south'
    | '/farms/weather'
    | '/life/culturals'
    | '/life/events'
    | '/life/fee-payment'
    | '/life/hostel'
    | '/life/newsletter'
    | '/life/placement'
    | '/about'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/faculty'
    | '/gallery'
    | '/about/anti-ragging'
    | '/about/approvals'
    | '/about/board-of-studies'
    | '/about/chairman'
    | '/about/icar'
    | '/about/principal'
    | '/about/sexual-harassment'
    | '/about/vision-mission'
    | '/academics/computer-center'
    | '/academics/courses'
    | '/academics/exam-pattern'
    | '/academics/library'
    | '/academics/nss'
    | '/academics/physical-education'
    | '/academics/smart-class'
    | '/academics/yoga'
    | '/divisions/agriculture-engineering'
    | '/divisions/crop-improvement'
    | '/divisions/crop-management'
    | '/divisions/horticulture'
    | '/divisions/plant-protection'
    | '/divisions/social-science'
    | '/farms/north'
    | '/farms/south'
    | '/farms/weather'
    | '/life/culturals'
    | '/life/events'
    | '/life/fee-payment'
    | '/life/hostel'
    | '/life/newsletter'
    | '/life/placement'
    | '/about/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FacultyRoute: typeof FacultyRoute
  GalleryRoute: typeof GalleryRoute
  AboutAntiRaggingRoute: typeof AboutAntiRaggingRoute
  AboutApprovalsRoute: typeof AboutApprovalsRoute
  AboutBoardOfStudiesRoute: typeof AboutBoardOfStudiesRoute
  AboutChairmanRoute: typeof AboutChairmanRoute
  AboutIcarRoute: typeof AboutIcarRoute
  AboutPrincipalRoute: typeof AboutPrincipalRoute
  AboutSexualHarassmentRoute: typeof AboutSexualHarassmentRoute
  AboutVisionMissionRoute: typeof AboutVisionMissionRoute
  AcademicsComputerCenterRoute: typeof AcademicsComputerCenterRoute
  AcademicsCoursesRoute: typeof AcademicsCoursesRoute
  AcademicsExamPatternRoute: typeof AcademicsExamPatternRoute
  AcademicsLibraryRoute: typeof AcademicsLibraryRoute
  AcademicsNssRoute: typeof AcademicsNssRoute
  AcademicsPhysicalEducationRoute: typeof AcademicsPhysicalEducationRoute
  AcademicsSmartClassRoute: typeof AcademicsSmartClassRoute
  AcademicsYogaRoute: typeof AcademicsYogaRoute
  DivisionsAgricultureEngineeringRoute: typeof DivisionsAgricultureEngineeringRoute
  DivisionsCropImprovementRoute: typeof DivisionsCropImprovementRoute
  DivisionsCropManagementRoute: typeof DivisionsCropManagementRoute
  DivisionsHorticultureRoute: typeof DivisionsHorticultureRoute
  DivisionsPlantProtectionRoute: typeof DivisionsPlantProtectionRoute
  DivisionsSocialScienceRoute: typeof DivisionsSocialScienceRoute
  FarmsNorthRoute: typeof FarmsNorthRoute
  FarmsSouthRoute: typeof FarmsSouthRoute
  FarmsWeatherRoute: typeof FarmsWeatherRoute
  LifeCulturalsRoute: typeof LifeCulturalsRoute
  LifeEventsRoute: typeof LifeEventsRoute
  LifeFeePaymentRoute: typeof LifeFeePaymentRoute
  LifeHostelRoute: typeof LifeHostelRoute
  LifeNewsletterRoute: typeof LifeNewsletterRoute
  LifePlacementRoute: typeof LifePlacementRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life/placement': {
      id: '/life/placement'
      path: '/life/placement'
      fullPath: '/life/placement'
      preLoaderRoute: typeof LifePlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life/newsletter': {
      id: '/life/newsletter'
      path: '/life/newsletter'
      fullPath: '/life/newsletter'
      preLoaderRoute: typeof LifeNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life/hostel': {
      id: '/life/hostel'
      path: '/life/hostel'
      fullPath: '/life/hostel'
      preLoaderRoute: typeof LifeHostelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life/fee-payment': {
      id: '/life/fee-payment'
      path: '/life/fee-payment'
      fullPath: '/life/fee-payment'
      preLoaderRoute: typeof LifeFeePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life/events': {
      id: '/life/events'
      path: '/life/events'
      fullPath: '/life/events'
      preLoaderRoute: typeof LifeEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life/culturals': {
      id: '/life/culturals'
      path: '/life/culturals'
      fullPath: '/life/culturals'
      preLoaderRoute: typeof LifeCulturalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/weather': {
      id: '/farms/weather'
      path: '/farms/weather'
      fullPath: '/farms/weather'
      preLoaderRoute: typeof FarmsWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/south': {
      id: '/farms/south'
      path: '/farms/south'
      fullPath: '/farms/south'
      preLoaderRoute: typeof FarmsSouthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/north': {
      id: '/farms/north'
      path: '/farms/north'
      fullPath: '/farms/north'
      preLoaderRoute: typeof FarmsNorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions/social-science': {
      id: '/divisions/social-science'
      path: '/divisions/social-science'
      fullPath: '/divisions/social-science'
      preLoaderRoute: typeof DivisionsSocialScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions/plant-protection': {
      id: '/divisions/plant-protection'
      path: '/divisions/plant-protection'
      fullPath: '/divisions/plant-protection'
      preLoaderRoute: typeof DivisionsPlantProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions/horticulture': {
      id: '/divisions/horticulture'
      path: '/divisions/horticulture'
      fullPath: '/divisions/horticulture'
      preLoaderRoute: typeof DivisionsHorticultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions/crop-management': {
      id: '/divisions/crop-management'
      path: '/divisions/crop-management'
      fullPath: '/divisions/crop-management'
      preLoaderRoute: typeof DivisionsCropManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions/crop-improvement': {
      id: '/divisions/crop-improvement'
      path: '/divisions/crop-improvement'
      fullPath: '/divisions/crop-improvement'
      preLoaderRoute: typeof DivisionsCropImprovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions/agriculture-engineering': {
      id: '/divisions/agriculture-engineering'
      path: '/divisions/agriculture-engineering'
      fullPath: '/divisions/agriculture-engineering'
      preLoaderRoute: typeof DivisionsAgricultureEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/yoga': {
      id: '/academics/yoga'
      path: '/academics/yoga'
      fullPath: '/academics/yoga'
      preLoaderRoute: typeof AcademicsYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/smart-class': {
      id: '/academics/smart-class'
      path: '/academics/smart-class'
      fullPath: '/academics/smart-class'
      preLoaderRoute: typeof AcademicsSmartClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/physical-education': {
      id: '/academics/physical-education'
      path: '/academics/physical-education'
      fullPath: '/academics/physical-education'
      preLoaderRoute: typeof AcademicsPhysicalEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/nss': {
      id: '/academics/nss'
      path: '/academics/nss'
      fullPath: '/academics/nss'
      preLoaderRoute: typeof AcademicsNssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/library': {
      id: '/academics/library'
      path: '/academics/library'
      fullPath: '/academics/library'
      preLoaderRoute: typeof AcademicsLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/exam-pattern': {
      id: '/academics/exam-pattern'
      path: '/academics/exam-pattern'
      fullPath: '/academics/exam-pattern'
      preLoaderRoute: typeof AcademicsExamPatternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/courses': {
      id: '/academics/courses'
      path: '/academics/courses'
      fullPath: '/academics/courses'
      preLoaderRoute: typeof AcademicsCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/computer-center': {
      id: '/academics/computer-center'
      path: '/academics/computer-center'
      fullPath: '/academics/computer-center'
      preLoaderRoute: typeof AcademicsComputerCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/vision-mission': {
      id: '/about/vision-mission'
      path: '/about/vision-mission'
      fullPath: '/about/vision-mission'
      preLoaderRoute: typeof AboutVisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/sexual-harassment': {
      id: '/about/sexual-harassment'
      path: '/about/sexual-harassment'
      fullPath: '/about/sexual-harassment'
      preLoaderRoute: typeof AboutSexualHarassmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/principal': {
      id: '/about/principal'
      path: '/about/principal'
      fullPath: '/about/principal'
      preLoaderRoute: typeof AboutPrincipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/icar': {
      id: '/about/icar'
      path: '/about/icar'
      fullPath: '/about/icar'
      preLoaderRoute: typeof AboutIcarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/chairman': {
      id: '/about/chairman'
      path: '/about/chairman'
      fullPath: '/about/chairman'
      preLoaderRoute: typeof AboutChairmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/board-of-studies': {
      id: '/about/board-of-studies'
      path: '/about/board-of-studies'
      fullPath: '/about/board-of-studies'
      preLoaderRoute: typeof AboutBoardOfStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/approvals': {
      id: '/about/approvals'
      path: '/about/approvals'
      fullPath: '/about/approvals'
      preLoaderRoute: typeof AboutApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/anti-ragging': {
      id: '/about/anti-ragging'
      path: '/about/anti-ragging'
      fullPath: '/about/anti-ragging'
      preLoaderRoute: typeof AboutAntiRaggingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FacultyRoute: FacultyRoute,
  GalleryRoute: GalleryRoute,
  AboutAntiRaggingRoute: AboutAntiRaggingRoute,
  AboutApprovalsRoute: AboutApprovalsRoute,
  AboutBoardOfStudiesRoute: AboutBoardOfStudiesRoute,
  AboutChairmanRoute: AboutChairmanRoute,
  AboutIcarRoute: AboutIcarRoute,
  AboutPrincipalRoute: AboutPrincipalRoute,
  AboutSexualHarassmentRoute: AboutSexualHarassmentRoute,
  AboutVisionMissionRoute: AboutVisionMissionRoute,
  AcademicsComputerCenterRoute: AcademicsComputerCenterRoute,
  AcademicsCoursesRoute: AcademicsCoursesRoute,
  AcademicsExamPatternRoute: AcademicsExamPatternRoute,
  AcademicsLibraryRoute: AcademicsLibraryRoute,
  AcademicsNssRoute: AcademicsNssRoute,
  AcademicsPhysicalEducationRoute: AcademicsPhysicalEducationRoute,
  AcademicsSmartClassRoute: AcademicsSmartClassRoute,
  AcademicsYogaRoute: AcademicsYogaRoute,
  DivisionsAgricultureEngineeringRoute: DivisionsAgricultureEngineeringRoute,
  DivisionsCropImprovementRoute: DivisionsCropImprovementRoute,
  DivisionsCropManagementRoute: DivisionsCropManagementRoute,
  DivisionsHorticultureRoute: DivisionsHorticultureRoute,
  DivisionsPlantProtectionRoute: DivisionsPlantProtectionRoute,
  DivisionsSocialScienceRoute: DivisionsSocialScienceRoute,
  FarmsNorthRoute: FarmsNorthRoute,
  FarmsSouthRoute: FarmsSouthRoute,
  FarmsWeatherRoute: FarmsWeatherRoute,
  LifeCulturalsRoute: LifeCulturalsRoute,
  LifeEventsRoute: LifeEventsRoute,
  LifeFeePaymentRoute: LifeFeePaymentRoute,
  LifeHostelRoute: LifeHostelRoute,
  LifeNewsletterRoute: LifeNewsletterRoute,
  LifePlacementRoute: LifePlacementRoute,
  AboutIndexRoute: AboutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
